# Generated by Django 4.2.23 on 2025-08-02 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('cover_image_url', models.URLField(blank=True, null=True, verbose_name='帖子封面图片URL')),
                ('content', models.TextField(verbose_name='Markdown内容')),
                ('tags', models.CharField(blank=True, max_length=200, null=True, verbose_name='标签（逗号分隔）')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='自定义链接slug')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='帖子发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='帖子修改时间')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='帖子作者')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
                'ordering': ['-created_at'],
            },
        ),
    ]
