# Generated by Django 4.2.23 on 2025-08-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tech', '技术'), ('chat', '杂谈'), ('life', '生活')], default='tech', max_length=10, verbose_name='分区'),
        ),
    ]
