# Generated by Django 4.2.23 on 2025-08-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='click_count',
            field=models.PositiveIntegerField(default=0, verbose_name='点击数'),
        ),
    ]
