# Generated by Django 4.2.23 on 2025-07-30 08:07

from django.db import migrations
import users.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=users.fields.ImageURLField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
