# Generated by Django 4.2.23 on 2025-09-18 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_avatar_customuser_avatar_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='用户代理')),
                ('referer', models.URLField(blank=True, null=True, verbose_name='来源页面')),
                ('path', models.CharField(max_length=500, verbose_name='访问路径')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='会话ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '访客记录',
                'verbose_name_plural': '访客记录',
                'ordering': ['-timestamp'],
            },
        ),
    ]
